-- ============================================================
-- Phase 9: Missing Tables — Conversations, Coupons, Newsletter
-- Run this in Supabase SQL Editor
-- ============================================================

-- 1. CONVERSATIONS
create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  subject text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.conversations enable row level security;

-- 2. CONVERSATION PARTICIPANTS (join table)
create table if not exists public.conversation_participants (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  last_read_at timestamptz default now(),
  created_at timestamptz default now(),
  unique(conversation_id, user_id)
);

alter table public.conversation_participants enable row level security;

-- 3. MESSAGES
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz default now()
);

alter table public.messages enable row level security;

-- 4. COUPONS
create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_percent numeric(5,2) not null default 10,
  max_uses integer default null,
  used_count integer default 0,
  is_active boolean default true,
  expires_at timestamptz,
  created_at timestamptz default now()
);

alter table public.coupons enable row level security;

-- 5. NEWSLETTER SUBSCRIBERS
create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  subscribed_at timestamptz default now(),
  is_active boolean default true
);

alter table public.newsletter_subscribers enable row level security;

-- ============================================================
-- RLS POLICIES
-- ============================================================

-- Conversations: participants can read their own conversations
create policy "Participants can view conversations"
  on public.conversations for select
  using (
    exists (
      select 1 from public.conversation_participants
      where conversation_id = id and user_id = auth.uid()
    )
  );

create policy "Participants can update conversations"
  on public.conversations for update
  using (
    exists (
      select 1 from public.conversation_participants
      where conversation_id = id and user_id = auth.uid()
    )
  );

-- Conversation participants: can view own participations, insert if participant
create policy "Users can view own participations"
  on public.conversation_participants for select
  using (user_id = auth.uid());

create policy "Users can insert participations"
  on public.conversation_participants for insert
  with check (auth.uid() = user_id);

-- Messages: participants can view and insert
create policy "Participants can view messages"
  on public.messages for select
  using (
    exists (
      select 1 from public.conversation_participants
      where conversation_id = messages.conversation_id and user_id = auth.uid()
    )
  );

create policy "Participants can insert messages"
  on public.messages for insert
  with check (
    auth.uid() = sender_id
    and
    exists (
      select 1 from public.conversation_participants
      where conversation_id = messages.conversation_id and user_id = auth.uid()
    )
  );

-- Coupons: public read for active, admin write
create policy "Anyone can read active coupons"
  on public.coupons for select
  using (is_active = true and (expires_at is null or expires_at > now()));

create policy "Admin can manage coupons"
  on public.coupons for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- Newsletter: anyone can insert (subscribe), only admin can read/manage
create policy "Anyone can subscribe"
  on public.newsletter_subscribers for insert
  with check (true);

create policy "Admin can manage subscribers"
  on public.newsletter_subscribers for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );
