export interface DummyProduct {
  id: number;
  slug: string;
  title: string;
  price: number; // -1 for Request a Quote, 0 for Free, positive for normal price
  discountPercent: number | null;
  isFeatured: boolean;
  categoryName: string;
  sellerName: string;
  sellerSlug: string;
  rating: number | null;
  reviewCount: number;
  sku: string;
  inStock: boolean;
  description: string;
  brand: string;
  fabric: string;
  shippingLocation: string;
  images: string[];
  type?: 'physical' | 'digital';
  hasVariants?: boolean;
  sizes?: string[];
  weight?: number | null;
}

export const dummyProducts: DummyProduct[] = [
  {
    id: 1,
    slug: "summer-fashion-top-lace",
    title: "Summer fashion top lace",
    price: 79,
    discountPercent: 17,
    isFeatured: true,
    categoryName: "Clothing",
    sellerName: "Trendshop",
    sellerSlug: "trendshop",
    rating: 3,
    reviewCount: 3,
    sku: "SFT-001",
    inStock: true,
    description: "Elegant summer lace top with comfortable fitting and premium look.",
    brand: "Trendshop",
    fabric: "Lace & Cotton",
    shippingLocation: "Berlin, Germany",
    images: ["product-1"],
    type: "physical",
    hasVariants: true,
    sizes: ["S", "M", "L", "XL"],
    weight: 300,
  },
  {
    id: 2,
    slug: "women-lace-blouse-with-different-colors",
    title: "Women lace blouse with different colors",
    price: 79,
    discountPercent: 12,
    isFeatured: true,
    categoryName: "Clothing",
    sellerName: "Trendshop",
    sellerSlug: "trendshop",
    rating: null,
    reviewCount: 5,
    sku: "WLB-002",
    inStock: true,
    description: "Beautiful lace blouse for women, available in various colors.",
    brand: "Trendshop",
    fabric: "Polyester",
    shippingLocation: "Paris, France",
    images: ["product-2"],
  },
  {
    id: 3,
    slug: "floral-women-sundress",
    title: "Floral women sundress",
    price: 89,
    discountPercent: 10,
    isFeatured: true,
    categoryName: "Clothing",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: 5,
    reviewCount: 4,
    sku: "FWS-003",
    inStock: true,
    description: "Bright floral design sundress, perfect for beachwear and warm days.",
    brand: "Admin",
    fabric: "Chiffon",
    shippingLocation: "Rome, Italy",
    images: ["product-3"],
  },
  {
    id: 4,
    slug: "gucci-nylon-fabric-smart-backpack",
    title: "Gucci nylon fabric smart backpack",
    price: 69,
    discountPercent: 20,
    isFeatured: false,
    categoryName: "Clothing",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: null,
    reviewCount: 2,
    sku: "GNS-004",
    inStock: true,
    description: "Premium nylon fabric smart backpack with multi-compartments.",
    brand: "Gucci",
    fabric: "Nylon",
    shippingLocation: "Milan, Italy",
    images: ["product-4"],
  },
  {
    id: 5,
    slug: "black-sneakers-with-white-sole",
    title: "Black sneakers with white sole",
    price: 89,
    discountPercent: 22,
    isFeatured: false,
    categoryName: "Shoes",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: null,
    reviewCount: 0,
    sku: "BSW-005",
    inStock: true,
    description: "Sporty black sneakers featuring contrasting white cushioned soles.",
    brand: "Admin",
    fabric: "Mesh & Rubber",
    shippingLocation: "London, UK",
    images: ["product-5"],
  },
  {
    id: 6,
    slug: "women-kipling-bailey-saddle-handbag",
    title: "Women kipling bailey saddle handbag",
    price: 69,
    discountPercent: 14,
    isFeatured: false,
    categoryName: "Clothing",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: null,
    reviewCount: 1,
    sku: "KBS-006",
    inStock: true,
    description: "Compact and durable saddle handbag for everyday convenience.",
    brand: "Kipling",
    fabric: "Canvas",
    shippingLocation: "Brussels, Belgium",
    images: ["product-6"],
  },
  {
    id: 7,
    slug: "cobalt-man-t-shirt-all-colors",
    title: "Cobalt man t-shirt all colors",
    price: -1, // Request a Quote
    discountPercent: null,
    isFeatured: true,
    categoryName: "Clothing",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: null,
    reviewCount: 0,
    sku: "CMT-007",
    inStock: true,
    description: "Request a custom quote for bulk order of cobalt t-shirts in any color.",
    brand: "Admin",
    fabric: "Cotton",
    shippingLocation: "Berlin, Germany",
    images: ["product-7"],
  },
  {
    id: 8,
    slug: "blanket-comfort-couch-pillow",
    title: "Blanket comfort couch pillow",
    price: 39,
    discountPercent: null,
    isFeatured: true,
    categoryName: "Home & Living",
    sellerName: "Trendshop",
    sellerSlug: "trendshop",
    rating: null,
    reviewCount: 1,
    sku: "BCC-008",
    inStock: true,
    description: "Super soft throw pillow and blanket set for your living room couch.",
    brand: "Trendshop",
    fabric: "Velvet",
    shippingLocation: "Munich, Germany",
    images: ["product-8"],
  },
  {
    id: 9,
    slug: "handmade-cute-handbag",
    title: "Handmade cute handbag",
    price: 45,
    discountPercent: 33, // price is $30 after discount
    isFeatured: true,
    categoryName: "Clothing",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: null,
    reviewCount: 0,
    sku: "HCH-009",
    inStock: true,
    description: "Unique hand-woven cute handbag with detailed straw weaving.",
    brand: "Admin",
    fabric: "Straw & Leather",
    shippingLocation: "Bali, Indonesia",
    images: ["product-9"],
  },
  {
    id: 10,
    slug: "light-blue-women-shirt",
    title: "Light blue women shirt",
    price: 69,
    discountPercent: 29, // price is $49 after discount
    isFeatured: true,
    categoryName: "Clothing",
    sellerName: "Trendshop",
    sellerSlug: "trendshop",
    rating: null,
    reviewCount: 0,
    sku: "LBW-010",
    inStock: true,
    description: "Casual light blue cotton shirt for women, perfect for summer days.",
    brand: "Trendshop",
    fabric: "Cotton",
    shippingLocation: "Frankfurt, Germany",
    images: ["product-10"],
  },
  {
    id: 11,
    slug: "sun-hat-for-women-protection-cap",
    title: "Sun hat for women protection cap",
    price: 29,
    discountPercent: null,
    isFeatured: true,
    categoryName: "Clothing",
    sellerName: "Trendshop",
    sellerSlug: "trendshop",
    rating: 4.5,
    reviewCount: 1,
    sku: "SHW-011",
    inStock: true,
    description: "Wide-brim straw hat providing excellent UV sun protection.",
    brand: "Trendshop",
    fabric: "Straw",
    shippingLocation: "Berlin, Germany",
    images: ["product-11"],
  },
  {
    id: 12,
    slug: "moment-of-inspiration-piano-music",
    title: "Moment of inspiration piano music",
    price: 34,
    discountPercent: 55, // price is $15 after discount
    isFeatured: true,
    categoryName: "Video & Audio",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: null,
    reviewCount: 1,
    sku: "MIP-012",
    inStock: true,
    description: "Inspiring classic piano background music track for digital downloads.",
    brand: "Admin",
    fabric: "Digital",
    shippingLocation: "Internet",
    images: ["product-12"],
    type: "digital",
    hasVariants: false,
    weight: null,
  },
  {
    id: 13,
    slug: "women-casual-dress",
    title: "Women casual dress",
    price: 56,
    discountPercent: null,
    isFeatured: true,
    categoryName: "Clothing",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: null,
    reviewCount: 1,
    sku: "WCD-013",
    inStock: true,
    description: "Simple yet fashionable casual dress for everyday outings.",
    brand: "Admin",
    fabric: "Linen",
    shippingLocation: "Rome, Italy",
    images: ["product-13"],
  },
  {
    id: 14,
    slug: "adorable-animals-photo-pack",
    title: "Adorable animals photo pack",
    price: 0, // Free
    discountPercent: null,
    isFeatured: true,
    categoryName: "Graphics & Photos",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: null,
    reviewCount: 0,
    sku: "AAP-014",
    inStock: true,
    description: "A free collection of high-resolution royalty free animal stock photos.",
    brand: "Admin",
    fabric: "Digital",
    shippingLocation: "Internet",
    images: ["product-14"],
  },
  {
    id: 15,
    slug: "sneaker-shoes-men",
    title: "Sneaker shoes men",
    price: 100,
    discountPercent: 11, // price is $89 after discount
    isFeatured: true,
    categoryName: "Shoes",
    sellerName: "Trendshop",
    sellerSlug: "trendshop",
    rating: null,
    reviewCount: 0,
    sku: "SSM-015",
    inStock: true,
    description: "Comfortable urban sneakers for active men, lightweight design.",
    brand: "Trendshop",
    fabric: "Synthetic",
    shippingLocation: "Berlin, Germany",
    images: ["product-15"],
  },
  {
    id: 16,
    slug: "animation-of-popular-vacation-spots",
    title: "Animation of popular vacation spots",
    price: 15,
    discountPercent: 33, // price is $10 after discount
    isFeatured: true,
    categoryName: "Graphics & Photos",
    sellerName: "Trendshop",
    sellerSlug: "trendshop",
    rating: null,
    reviewCount: 0,
    sku: "AVS-016",
    inStock: true,
    description: "Charming loop animation assets featuring world vacation destinations.",
    brand: "Trendshop",
    fabric: "Digital",
    shippingLocation: "Internet",
    images: ["product-16"],
  },
  {
    id: 17,
    slug: "colorful-women-scarves",
    title: "Colorful women scarves",
    price: 45,
    discountPercent: 11, // price is $40 after discount
    isFeatured: false,
    categoryName: "Clothing",
    sellerName: "Trendshop",
    sellerSlug: "trendshop",
    rating: null,
    reviewCount: 1,
    sku: "CWS-017",
    inStock: true,
    description: "Soft printed scarf, perfect accessory to add splash of color to your outfit.",
    brand: "Trendshop",
    fabric: "Silk",
    shippingLocation: "Berlin, Germany",
    images: ["product-17"],
  },
  {
    id: 18,
    slug: "womens-ankle-boot-with-different-colors",
    title: "Women's ankle boot with different colors",
    price: 69,
    discountPercent: 14, // price is $59 after discount
    isFeatured: false,
    categoryName: "Shoes",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: null,
    reviewCount: 0,
    sku: "WAB-018",
    inStock: true,
    description: "Chic leather ankle boots available in multiple stylish colors.",
    brand: "Admin",
    fabric: "Genuine Leather",
    shippingLocation: "Rome, Italy",
    images: ["product-18"],
  },
  {
    id: 19,
    slug: "navy-polka-dot-dress",
    title: "Navy polka dot dress",
    price: 150,
    discountPercent: 13, // price is $130 after discount
    isFeatured: false,
    categoryName: "Clothing",
    sellerName: "Trendshop",
    sellerSlug: "trendshop",
    rating: null,
    reviewCount: 2,
    sku: "NPD-019",
    inStock: true,
    description: "Classic retro polka dot print navy blue dress with a cinched waist.",
    brand: "Trendshop",
    fabric: "Cotton",
    shippingLocation: "Berlin, Germany",
    images: ["product-19"],
  },
  {
    id: 20,
    slug: "modern-grey-couch-and-pillows",
    title: "Modern grey couch and pillows",
    price: 299,
    discountPercent: null,
    isFeatured: false,
    categoryName: "Home & Living",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: 5,
    reviewCount: 1,
    sku: "MGC-020",
    inStock: true,
    description: "Contemporary gray fabric couch with matching soft decorative pillows.",
    brand: "Admin",
    fabric: "Fabric & Wood",
    shippingLocation: "Rome, Italy",
    images: ["product-20"],
  },
  {
    id: 21,
    slug: "black-fashion-women-backpack",
    title: "Black fashion women backpack",
    price: -1, // Request a Quote
    discountPercent: null,
    isFeatured: false,
    categoryName: "Clothing",
    sellerName: "Trendshop",
    sellerSlug: "trendshop",
    rating: null,
    reviewCount: 2,
    sku: "BFB-021",
    inStock: true,
    description: "Sleek and classy black leather fashion backpack designed for women.",
    brand: "Trendshop",
    fabric: "Suede Leather",
    shippingLocation: "Berlin, Germany",
    images: ["product-21"],
  },
  {
    id: 22,
    slug: "handcrafted-decorative-pillow-for-a-luxurious",
    title: "Handcrafted decorative pillow for a luxurious...",
    price: 69,
    discountPercent: 14, // price is $59 after discount
    isFeatured: false,
    categoryName: "Home & Living",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: null,
    reviewCount: 1,
    sku: "HDP-022",
    inStock: true,
    description: "Add a luxurious accent to your sofa with this handcrafted decorative pillow.",
    brand: "Admin",
    fabric: "Velour",
    shippingLocation: "Rome, Italy",
    images: ["product-22"],
  },
  {
    id: 23,
    slug: "black-midi-skirt-with-white-flowers",
    title: "Black midi skirt with white flowers",
    price: 55,
    discountPercent: 12, // price is $48 after discount
    isFeatured: false,
    categoryName: "Clothing",
    sellerName: "Trendshop",
    sellerSlug: "trendshop",
    rating: 5,
    reviewCount: 1,
    sku: "BMS-023",
    inStock: true,
    description: "Flowing black midi skirt patterned with subtle white floral prints.",
    brand: "Trendshop",
    fabric: "Rayon",
    shippingLocation: "Berlin, Germany",
    images: ["product-23"],
  },
  {
    id: 24,
    slug: "animal-colorful-digital-prints",
    title: "Animal colorful digital prints",
    price: 39,
    discountPercent: 25, // price is $29 after discount
    isFeatured: false,
    categoryName: "Graphics & Photos",
    sellerName: "Trendshop",
    sellerSlug: "trendshop",
    rating: 5,
    reviewCount: 1,
    sku: "ACD-024",
    inStock: true,
    description: "Vibrant high resolution animal colorful abstract print for home walls.",
    brand: "Trendshop",
    fabric: "Digital",
    shippingLocation: "Internet",
    images: ["product-24"],
  },
  {
    id: 25,
    slug: "seychelles-womens-brown-ankle-boots",
    title: "Seychelles women's brown ankle boots",
    price: 79,
    discountPercent: null,
    isFeatured: false,
    categoryName: "Shoes",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: null,
    reviewCount: 0,
    sku: "SAB-025",
    inStock: true,
    description: "Vintage inspired comfortable Seychelles ankle boots in brown suede.",
    brand: "Admin",
    fabric: "Suede Leather",
    shippingLocation: "Rome, Italy",
    images: ["product-25"],
  },
  {
    id: 26,
    slug: "ship-illustration-royalty-free-image",
    title: "Ship illustration royalty free image",
    price: 29,
    discountPercent: 48, // price is $15 after discount
    isFeatured: false,
    categoryName: "Graphics & Photos",
    sellerName: "Admin",
    sellerSlug: "admin",
    rating: null,
    reviewCount: 0,
    sku: "SIR-026",
    inStock: true,
    description: "Stunning detailed vector illustration of a vintage sailing ship.",
    brand: "Admin",
    fabric: "Digital",
    shippingLocation: "Internet",
    images: ["product-26"],
  },
];
